- hosts: all
  become: yes

  tasks:
  - include_role:
          name: hypervguest
    when: 
      - ansible_system_vendor == "Microsoft Corporation"
      - ansible_virtualization_role == "guest"
      - ansible_virtualization_type == "VirtualPC"
