- name: install bind daemon
  apt:
          name: bind9
          state: latest
          update_cache: yes

- name: start the bind daemon and make sure it starts on boot
  service:
          name: bind9
          state: started
          enabled: yes

- name: configure BIND options
  template:
          src: ../templates/{{ bind_options_file_name }}
          dest: "{{ bind_conf_directory }}/{{ bind_options_file_name }}"
          owner: root
          group: bind
          mode: 0644
          validate: /usr/sbin/named-checkconf %s
          backup: yes
  register: options

- name: configure master BIND zones
  template:
        src: ../templates/{{ bind_zone_conf_name }}.{{ dns_order }}
        dest: "{{ bind_conf_directory }}/{{ bind_zone_conf_name }}"
        owner: root
        group: bind
        mode: 0644
        validate: /usr/sbin/named-checkconf %s
        backup: yes
  register: zones

- name: populate zone files
  template:
          src: ../templates/db.zone
          dest: /tmp/db.{{ item.name|replace(":",".") }}
          owner: root
          group: bind
          mode: 0644
  loop: "{{ dns_lookup_zones }}"
  when: dns_order == "master"

- name: reload bind configuration
  command: rndc reconfig
  when: options.changed or zones.changed
