- name: install bind daemon
  apt:
          name: bind9
          state: latest
          update_cache: yes

- name: start the bind daemon and make sure it starts on boot
  service:
          name: bind9
          state: started
          enabled: yes

- name: configure BIND options
  template:
          src: ../templates/{{ bind_options_file_name }}
          dest: "{{ bind_conf_directory }}/{{ bind_options_file_name }}"
          owner: root
          group: bind
          mode: 0644
          validate: /usr/sbin/named-checkconf %s
          backup: yes
  register: options

- name: configure BIND zones
  template:
        src: ../templates/{{ bind_zone_conf_name }}
        dest: /tmp/{{ bind_zone_conf_name }}
        owner: root
        group: bind
        mode: 0644

- name: reload bind configuration
  command: rndc reconfig
  when: options.changed
